name: "paddle_pre_det"
backend: "python"
max_batch_size: 6
input [
  {
    name: "images"
    data_type: TYPE_UINT8
    dims: [3,-1,-1]
  }
]
output [
  {
    name: "pre_det_output"
    data_type: TYPE_FP32
    dims: [3,-1,-1]
  },
  {
    name: "pre_det_shape_list"
    data_type: TYPE_FP32
    dims: [4]
  }
]
instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
]