name: "paddle_text_rec"
platform: "ensemble"
max_batch_size: 6
input [
  {
    name: "pre_images"
    data_type: TYPE_UINT8
    dims: [3,-1,-1]
  },
  {
    name: "pre_dt_boxes"
    data_type: TYPE_FP32
    dims: [-1,4,2]
  }
]
output [
  {
    name: "infer_text_rec_output"
    data_type: TYPE_FP32
    dims: [-1, 97]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "paddle_pre_rec"
      model_version: -1
      input_map {
        key: "pre_images"
        value: "pre_images"
      }
      input_map {
        key: "pre_dt_boxes"
        value: "pre_dt_boxes"
      }
      output_map {
        key: "pre_rec_output"
        value: "x"
      }
    },
    {
      model_name: "paddle_infer_text_rec"
      model_version: -1
      input_map {
        key: "x"
        value: "x"
      }
      output_map {
        key: "softmax_2.tmp_0"
        value: "infer_text_rec_output"
      }
    }
  ]
}