name: "ocr"
platform: "ensemble"
max_batch_size: 6
input [
  {
    name: "images"
    data_type: TYPE_UINT8
    dims: [3,-1,-1]
  }
]
output [
  {
    name: "text_det_output"
    data_type: TYPE_FP32
    dims: [-1,4,2]
  },
  {
    name: "text_rec_output"
    data_type: TYPE_FP32
    dims: [-1,50]
  },
  {
    name: "text_rec_output_score"
    data_type: TYPE_FP32
    dims: [-1]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "paddle_text_det"
      model_version: -1
      input_map {
        key: "images"
        value: "images"
      }
      output_map {
        key: "text_det_output"
        value: "text_det_output"
      }
    },
    {
      model_name: "paddle_text_rec"
      model_version: -1
      input_map {
        key: "images"
        value: "images"
      }
      input_map {
        key: "pre_dt_boxes"
        value: "text_det_output"
      }
      output_map {
        key: "text_rec_output"
        value: "text_rec_output"
      }      
      output_map {
        key: "text_rec_output_score"
        value: "text_rec_output_score"
      }
    }
  ]
}
