name: "paddle_text_det"
platform: "ensemble"
max_batch_size: 6
input [
  {
    name: "images"
    data_type: TYPE_UINT8
    dims: [3,-1,-1]
  }
]
output [
  {
    name: "text_det_output"
    data_type: TYPE_FP32
    dims: [-1,4,2]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "paddle_pre_det"
      model_version: -1
      input_map {
        key: "images"
        value: "images"
      }
      output_map {
        key: "pre_det_output"
        value: "x"
      }
      output_map {
        key: "pre_det_shape_list"
        value: "post_shape_list_input"
      }
    },
    {
      model_name: "paddle_infer_text_det"
      model_version: -1
      input_map {
        key: "x"
        value: "x"
      }
      output_map {
        key: "sigmoid_0.tmp_0"
        value: "post_det_input"
      }
    },
    {
      model_name: "paddle_post_det"
      model_version: -1
      input_map {
        key: "post_det_input"
        value: "post_det_input"
      }
      input_map {
        key: "post_shape_list_input"
        value: "post_shape_list_input"
      }
      output_map {
        key: "post_det_output"
        value: "text_det_output"
      }
    }
  ]
}
